/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#6ffbbe',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#adc7f7',
        'primary-fixed': '#d6e3ff',
        'outline-variant': '#c4c6cf',
        'secondary-container': '#645efb',
        'on-tertiary-fixed': '#002113',
        'surface-container-low': '#eff4ff',
        'surface-variant': '#d3e4fe',
        surface: '#f8f9ff',
        'primary-container': '#1a365d',
        'secondary-fixed': '#e2dfff',
        'on-background': '#0b1c30',
        'tertiary-container': '#003e28',
        'on-secondary-fixed-variant': '#3323cc',
        'on-error-container': '#93000a',
        'surface-container': '#e5eeff',
        primary: '#002045',
        'surface-tint': '#455f88',
        'on-tertiary-container': '#00b47d',
        tertiary: '#002617',
        'on-tertiary-fixed-variant': '#005236',
        'inverse-on-surface': '#eaf1ff',
        'surface-container-high': '#dce9ff',
        'on-surface-variant': '#43474e',
        'on-surface': '#0b1c30',
        error: '#ba1a1a',
        outline: '#74777f',
        'on-primary-fixed': '#001b3c',
        'secondary-fixed-dim': '#c3c0ff',
        'error-container': '#ffdad6',
        'inverse-primary': '#adc7f7',
        'on-primary-container': '#86a0cd',
        'surface-dim': '#cbdbf5',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#2d476f',
        'on-error': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        background: '#f8f9ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-tertiary': '#ffffff',
        secondary: '#4b41e1',
        'on-secondary-fixed': '#0f0069',
        'surface-bright': '#f8f9ff',
        'inverse-surface': '#213145',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        gutter: '24px', sm: '8px', base: '8px', md: '16px', 'margin-mobile': '16px',
        '2xl': '48px', xl: '32px', '3xl': '64px', 'margin-desktop': '48px', lg: '24px', xs: '4px',
      },
      fontFamily: { sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'] },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
