import { useQuery } from '@tanstack/react-query';
import { distributorApi } from '../../lib/api';
import Icon from '../../components/Icon';

const inr = (v) => `₹${Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dt = (v) => (v ? new Date(v).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '');

/** GST grouped by rate for the tax summary. */
function gstBreakup(items = []) {
  const m = new Map();
  items.forEach((it) => {
    const rate = Number(it.gstRate || 0);
    const taxable = Number(it.lineTotal || 0);
    const tax = taxable * (rate / 100);
    const cur = m.get(rate) || { taxable: 0, tax: 0 };
    cur.taxable += taxable; cur.tax += tax;
    m.set(rate, cur);
  });
  return [...m.entries()].sort((a, b) => a[0] - b[0]);
}

export default function InvoiceModal({ order, retailer, onClose }) {
  const { data: dist } = useQuery({ queryKey: ['dist-profile'], queryFn: distributorApi.profile });
  const items = order.items || [];
  const breakup = gstBreakup(items);

  const print = () => {
    const w = window.open('', '_blank', 'width=800,height=900');
    if (!w) return;
    const rows = items.map((it) => `
      <tr>
        <td>${it.productName}</td>
        <td style="text-align:right">${String(it.quantity)}</td>
        <td style="text-align:right">${inr(it.unitPrice)}</td>
        <td style="text-align:right">${String(it.gstRate)}%</td>
        <td style="text-align:right">${inr(it.lineTotal)}</td>
      </tr>`).join('');
    const taxRows = breakup.map(([rate, v]) => `
      <tr><td>GST @ ${rate}%</td><td style="text-align:right">${inr(v.taxable)}</td><td style="text-align:right">${inr(v.tax)}</td></tr>`).join('');
    w.document.write(`
      <html><head><title>Invoice ${order.orderNumber}</title>
      <style>
        body{font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;padding:32px;font-size:13px}
        h1{font-size:20px;margin:0}
        table{width:100%;border-collapse:collapse;margin-top:12px}
        th,td{border-bottom:1px solid #ddd;padding:6px 8px;text-align:left}
        th{background:#f3f3f3}
        .muted{color:#666}
        .right{text-align:right}
        .totals{margin-top:16px;width:280px;float:right}
        .totals td{border:none;padding:3px 8px}
        .grand{font-size:16px;font-weight:bold;border-top:2px solid #333}
      </style></head><body>
      <div style="display:flex;justify-content:space-between">
        <div>
          <h1>${dist?.shopName || dist?.ownerName || 'Tax Invoice'}</h1>
          <div class="muted">${dist?.address || ''} ${dist?.city || ''} ${dist?.state || ''} ${dist?.pincode || ''}</div>
          <div class="muted">${dist?.phone || ''}</div>
        </div>
        <div style="text-align:right">
          <h1>INVOICE</h1>
          <div class="muted">${order.orderNumber}</div>
          <div class="muted">${dt(order.placedAt)}</div>
        </div>
      </div>
      <div style="margin-top:16px"><strong>Bill to:</strong> ${retailer?.shopName || ''} ${retailer?.ownerName ? '· ' + retailer.ownerName : ''}<br/>
        <span class="muted">${retailer?.phone || ''} ${retailer?.city ? '· ' + retailer.city : ''}</span></div>
      <table>
        <thead><tr><th>Item</th><th class="right">Qty</th><th class="right">Rate</th><th class="right">GST</th><th class="right">Amount</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <table style="margin-top:12px;width:60%">
        <thead><tr><th>Tax</th><th class="right">Taxable</th><th class="right">Tax</th></tr></thead>
        <tbody>${taxRows}</tbody>
      </table>
      <table class="totals">
        <tr><td>Subtotal</td><td class="right">${inr(order.subtotal)}</td></tr>
        <tr><td>GST</td><td class="right">${inr(order.taxAmount)}</td></tr>
        <tr class="grand"><td>Total</td><td class="right">${inr(order.totalAmount)}</td></tr>
      </table>
      <div style="clear:both;margin-top:48px" class="muted">Generated by VyaparMantra · This is a computer-generated invoice.</div>
      <script>window.onload=function(){window.print();}</script>
      </body></html>`);
    w.document.close();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-margin-mobile">
      <div className="absolute inset-0 bg-black/40" onClick={onClose} />
      <div className="relative bg-surface-container-lowest rounded-2xl shadow-xl w-full max-w-lg p-lg space-y-md max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between">
          <h3 className="text-headline-md text-on-surface">Invoice · {order.orderNumber}</h3>
          <button onClick={onClose} className="text-on-surface-variant hover:text-on-surface"><Icon name="close" /></button>
        </div>

        <div className="text-label-md">
          <div className="flex justify-between">
            <div>
              <div className="font-bold text-on-surface">{dist?.shopName || 'Your business'}</div>
              <div className="text-on-surface-variant">{[dist?.city, dist?.state].filter(Boolean).join(', ')}</div>
            </div>
            <div className="text-right text-on-surface-variant">{dt(order.placedAt)}</div>
          </div>
          <div className="mt-sm text-on-surface-variant">Bill to: <span className="font-medium text-on-surface">{retailer?.shopName || `Retailer #${order.retailerId}`}</span></div>
        </div>

        <table className="w-full text-label-md">
          <thead><tr className="text-on-surface-variant text-label-sm">
            <th className="text-left py-1">Item</th><th className="text-right py-1">Qty</th>
            <th className="text-right py-1">Rate</th><th className="text-right py-1">GST</th><th className="text-right py-1">Amount</th>
          </tr></thead>
          <tbody className="divide-y divide-surface-variant">
            {items.map((it, i) => (
              <tr key={i}>
                <td className="py-1.5 text-on-surface">{it.productName}</td>
                <td className="py-1.5 text-right text-on-surface-variant">{String(it.quantity)}</td>
                <td className="py-1.5 text-right text-on-surface-variant">{inr(it.unitPrice)}</td>
                <td className="py-1.5 text-right text-on-surface-variant">{String(it.gstRate)}%</td>
                <td className="py-1.5 text-right text-on-surface font-medium">{inr(it.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex flex-col items-end gap-0.5 text-label-md">
          <div className="flex gap-xl"><span className="text-on-surface-variant">Subtotal</span><span>{inr(order.subtotal)}</span></div>
          <div className="flex gap-xl"><span className="text-on-surface-variant">GST</span><span>{inr(order.taxAmount)}</span></div>
          <div className="flex gap-xl text-headline-md font-bold text-on-surface border-t border-surface-variant pt-1"><span>Total</span><span>{inr(order.totalAmount)}</span></div>
        </div>

        <div className="flex justify-end gap-sm">
          <button onClick={onClose} className="px-lg py-2.5 rounded-xl text-label-md font-semibold text-on-surface hover:bg-surface-container">Close</button>
          <button onClick={print} className="bg-primary text-on-primary px-lg py-2.5 rounded-xl text-label-md font-semibold flex items-center gap-1">
            <Icon name="print" className="text-[18px]" /> Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
}
